# Header
menu:
  - {name: Home, path: /, class: fa-home, layout: 2}
  - {name: About, path: /about, class: fa-user, layout: 2}
  - {name: Archives, path: /archives, class: fa-archive, layout: 2}
  - {name: Tags, path: /tags, class: fa-tags, layout: 2}
  - {name: Pictures, path: /picture, class: fa-camera, layout: 2}
  - {name: Works, path: /works, class: fa-trophy, layout: 2}

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: top
widgets:
- category
- recent_posts
- links
- ukagaka

# Miscellaneous
google_analytics:
favicon:
twitter:
google_plus: 114761524022260759157
fb_admins:
fb_app_id:

# Google sitemap
google_siteVerification:
  id: 5mRgj8NanEMpGZuNfHNJNmH90RgNlrnJXsFlTaKD6Gs

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

## social
facebook_url: https://www.facebook.com/profile.php?id=100005630052910
github_url: https://github.com/liangzhenduo0608
google_plus_url: https://plus.google.com/114761524022260759157
twitter_url: https://twitter.com/liangzhenduo
#uhunt_url: http://uhunt.felix-halim.net/id/46705
